name: "Firefox UI Tests"
    
on:
    workflow_dispatch: {}
    schedule:
      - cron: "0 2 * * *"

env:
    browser: firefox-ios
    xcode_version: 15.4
    ios_version: 17.5
    ios_simulator_default: iPhone 15
    xcodebuild_scheme: Fennec
    xcodebuild_target: Client
    test_results_directory: /Users/runner/tmp
    
jobs:
    compile:
        name: Compile
        runs-on: macos-14
        steps:
            - name: Check out source code
              uses: actions/checkout@v4.1.7
            - name: Setup Xcode
              id: xcode
              run: |
                sudo rm -rf /Applications/Xcode.app
                sudo xcode-select -s /Applications/Xcode_${{ env.xcode_version }}.app/Contents/Developer
                xcodebuild -version
                ./checkout.sh
                ./bootstrap.sh --force
            - name: Compile source code
              id: compile
              run: |
                xcodebuild \
                  -resolvePackageDependencies \
                  -onlyUsePackageVersionsFromResolvedFile
                xcodebuild \
                  build-for-testing \
                  -scheme ${{ env.xcodebuild_scheme }} \
                  -target ${{ env.xcodebuild_target }} \
                  -derivedDataPath ~/DerivedData \
                  -destination 'platform=iOS Simulator,name=${{ env.ios_simulator_default }},OS=${{ env.ios_version }}'
              working-directory: ${{ env.browser }}
            - name: Compress Derived Data
              id: compress-dd
              run: |
                tar czf derived-data.tar.gz ~/DerivedData/Build/Products
            - name: Save Derived Data
              id: upload-derived-data
              uses: actions/upload-artifact@v4.3.4
              with:
                name: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
                path: ./derived-data.tar.gz
                retention-days: 2

    run-smoketests:
      name: Run smoke tests
      runs-on: macos-14
      needs: compile
      strategy:
        fail-fast: false
        matrix:
          ios_simulator: ['iPhone 15 Plus']
      steps:
      - name: Check out source code
        uses: actions/checkout@v4.1.7
      - name: Install packages
        id: packages
        run: |
          gem install xcpretty -v 0.3.0
          pip install blockkit==1.9.1
          npm install -g junit-report-merger@7.0.0       
      - name: Setup Xcode
        id: xcode
        run: |
          sudo rm -rf /Applications/Xcode.app
          sudo xcode-select -s /Applications/Xcode_${{ env.xcode_version }}.app/Contents/Developer
          xcodebuild -version
          ./checkout.sh
          ./bootstrap.sh --force
      - name: Get derived data
        id: download-derived-data
        uses: actions/download-artifact@v4
        with:
          name: xcode-cache-deriveddata-${{ github.workflow }}-${{ github.sha }}
      - name: Decompress derived data
        id: decompress-dd
        run: |
          tar xzf derived-data.tar.gz -C /
      - name: Run Smoketest1
        id: run-smoketest1
        run: |
          xcodebuild \
            test-without-building \
            -scheme ${{ env.xcodebuild_scheme }} \
            -target ${{ env.xcodebuild_target }} \
            -derivedDataPath ~/DerivedData \
            -destination 'platform=iOS Simulator,name=${{ matrix.ios_simulator }},OS=${{ env.ios_version }}' \
            -testPlan Smoketest1 \
            -test-iterations 10
            -resultBundlePath ${{ env.test_results_directory }}/results-smoketest1 \
            | tee xcodebuild.log | xcpretty -r junit --output ./junit-smoketest1.xml && exit ${PIPESTATUS[0]}
        working-directory:  ${{ env.browser }}
        continue-on-error: true
      - name: Run Smoketest2
        id: run-smoketest2
        run: |
          return 0
          # xcodebuild \
          #   test-without-building \
          #   -scheme ${{ env.xcodebuild_scheme }} \
          #   -target ${{ env.xcodebuild_target }} \
          #   -derivedDataPath ~/DerivedData \
          #   -destination 'platform=iOS Simulator,name=${{ matrix.ios_simulator }},OS=${{ env.ios_version }}' \
          #   -testPlan Smoketest2 \
          #   -resultBundlePath ${{ env.test_results_directory }}/results-smoketest2 \
          #   | tee xcodebuild.log | xcpretty -r junit --output ./junit-smoketest2.xml && exit ${PIPESTATUS[0]}
        working-directory:  ${{ env.browser }}
        continue-on-error: true
      - name: Run Smoketest3
        id: run-smoketest3
        run: |
          return 0
          # xcodebuild \
          #   test-without-building \
          #   -scheme ${{ env.xcodebuild_scheme }} \
          #   -target ${{ env.xcodebuild_target }} \
          #   -derivedDataPath ~/DerivedData \
          #   -destination 'platform=iOS Simulator,name=${{ matrix.ios_simulator }},OS=${{ env.ios_version }}' \
          #   -testPlan Smoketest3 \
          #   -resultBundlePath ${{ env.test_results_directory }}/results-smoketest3 \
          #   | tee xcodebuild.log | xcpretty -r junit --output ./junit-smoketest3.xml && exit ${PIPESTATUS[0]}
        working-directory:  ${{ env.browser }}
        continue-on-error: true
      - name: Run Smoketest4
        id: run-smoketest4
        run: |
          return 0
          # xcodebuild \
          #   test-without-building \
          #   -scheme ${{ env.xcodebuild_scheme }} \
          #   -target ${{ env.xcodebuild_target }} \
          #   -derivedDataPath ~/DerivedData \
          #   -destination 'platform=iOS Simulator,name=${{ matrix.ios_simulator }},OS=${{ env.ios_version }}' \
          #   -testPlan Smoketest4 \
          #   -resultBundlePath ${{ env.test_results_directory }}/results-smoketest4 \
          #   | tee xcodebuild.log | xcpretty -r junit --output ./junit-smoketest4.xml && exit ${PIPESTATUS[0]}
        working-directory:  ${{ env.browser }}
        continue-on-error: true
      - name: Determine pass/fail status
        id: passfail
        run: |
          echo "Smoketest1 status: "${{ steps.run-smoketest1.outcome }}
          echo "Smoketest2 status: "${{ steps.run-smoketest2.outcome }}
          echo "Smoketest3 status: "${{ steps.run-smoketest3.outcome }}
          echo "Smoketest4 status: "${{ steps.run-smoketest4.outcome }}
          if [[ ${{ steps.run-smoketest1.outcome }} != 'success' 
                || ${{ steps.run-smoketest2.outcome }} != 'success'  
                || ${{ steps.run-smoketest3.outcome }} != 'success' 
                || ${{ steps.run-smoketest4.outcome }} != 'success' ]]; then
            exit 1
          else
            exit 0
          fi
        continue-on-error: true
      - name: Print test report
        id: test-report
        run: |
          jrm combined.xml junit-*.xml
          python ../test-fixtures/ci/convert_junit_to_markdown.py --smoke --github --${{ env.browser }} ./combined.xml ./github.md
          cat github.md >> $GITHUB_STEP_SUMMARY
          python ../test-fixtures/ci/convert_junit_to_markdown.py --smoke --slack --${{ env.browser }} ./combined.xml ./slack.json
        working-directory:  ${{ env.browser }}
      - name: Upload junit files
        id: upload-junit
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.browser }}-smoketests-${{ matrix.ios_simulator }}-junit-${{ github.run_number }}
          path: ${{ env.browser }}/junit-*.xml
          retention-days: 90
      - name: Upload log file
        id: upload-log
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.browser }}-smoketests-${{ matrix.ios_simulator }}-xcodebuildlog-${{ github.run_number }}
          path: ${{ env.browser }}/xcodebuild.log
          retention-days: 90
      - name: Return fail status if a test fails
        run: |
          exit ${{ steps.passfail.outcome == 'success' && '0' || '1' }}   