name: "Focus Tests"
    
on:
    workflow_dispatch:

env:
    xcode_version: 15.4
    ios_version: 17.4
    ios_simulator: iPhone 15
    test_plan: SmokeTest
    
jobs:
    run-tests:
        name: Compile source code and run tests
        runs-on: macos-14
        steps:
            - name: Check out source code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install Python packages required
              run: |
                brew update
                pip3 install virtualenv pipenv
            - name: Setup Xcode
              run: |
                sudo rm -rf /Applications/Xcode.app
                sudo xcode-select -s /Applications/Xcode_${{ env.xcode_version }}.app/Contents/Developer
                xcodebuild -version
                xcrun simctl shutdown all
                xcrun simctl erase all
                ./checkout.sh
            - name: Compile source code
              run: |
                xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile
                xcodebuild build-for-testing -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ env.ios_simulator }},OS=${{ env.ios_version }}'
              working-directory: focus-ios
            - name: Run tests
              run: |
                xcodebuild test-without-building -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ env.ios_simulator }},OS=${{ env.ios_version }}' -testPlan ${{ env.test_plan }} -resultBundlePath ./tmp/results -only-testing:XCUITest/CopyPasteTest
              working-directory: focus-ios
              continue-on-error: true
            - name: Prettyprint test report
              run: |
                brew install xctesthtmlreport
                xchtmlreport ./tmp/results
              working-directory: focus-ios
            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1.1.1
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}
            - name: Upload to Google Cloud bucket
              uses: google-github-actions/upload-cloud-storage@v2
              with:
               process_gcloudignore: false
               path: 'focus-ios/tmp/index.html'
               destination: 'mobile-reports/public/focus-ios/${{ env.test_plan }}/result_${{ github.run_number }}'
            - name: Report to Slack
              id: slack
              uses: slackapi/slack-github-action@v1.26.0
              with:
                # This data can be any valid JSON from a previous step in the GitHub Action
                payload: |
                  {
                    "run_number": "${{ github.run_number }}",
                    "branch": "${{ github.ref_name }}",
                    "xcode_version": "${{ env.xcode_version }}",
                    "ios_simulator": "${{ env.ios_simulator }}",
                    "ios_version": "${{ env.ios_version }}",
                    "test_plan": "${{ env.test_plan }}",
                    "github_actions_url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                    "test_report_url": "https://storage.googleapis.com/mobile-reports/public/focus-ios/${{ env.test_plan }}/result_${{ github.run_number }}/index.html"
                  }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}