---
name: "Focus Smoke Tests"
    
on:
    workflow_dispatch:

env:
    xcode_version: 15.4
    ios_version: 17.4
    ios_simulator: iPhone 15
    
jobs:
    run-tests:
        name: Compile source code and run tests
        runs-on: macos-14
        steps:
            - name: Check out source code
              uses: actions/checkout@v4
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - name: Install Python packages required
              run: |
                brew update
                pip3 install virtualenv pipenv
            - name: Setup Xcode
              run: |
                sudo rm -rf /Applications/Xcode.app
                sudo xcode-select -s /Applications/Xcode_${{ env.xcode_version }}.app/Contents/Developer
                xcodebuild -version
                ./checkout.sh
            - name: Compile!
              run: |
                xcodebuild -resolvePackageDependencies -onlyUsePackageVersionsFromResolvedFile
                xcodebuild build-for-testing -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ env.ios_simulator }},OS=${{ env.ios_version }}'
              working-directory: focus-ios
            - name: Run smoke tests
              run: |
                xcodebuild test-without-building -scheme Focus -target XCUITest -configuration FocusDebug -destination 'platform=iOS Simulator,name=${{ env.ios_simulator }},OS=${{ env.ios_version }}' -testPlan SmokeTest -only-testing:XCUITest/CopyPasteTest
              working-directory: focus-ios
              continue-on-error: true
            - name: Report to Slack
              id: slack
              uses: slackapi/slack-github-action@v1.26.0
              with:
                # This data can be any valid JSON from a previous step in the GitHub Action
                payload: |
                  {
                    "test_plan": "smoke",
                    "xcode_version": ${{ env.xcode_version }},
                    "ios_simulator": ${{ env.ios_simulator }},
                    "ios_version": ${{ env.ios_version }}
                  }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}