name: "Test webhooks"
    
on:
    workflow_dispatch:

jobs:
    call-webhooks:
        runs-on: macos-14
        steps:
            - name: Hello World!
              run: |
                echo "Hello World!"
            - name: Report to Slack
              id: slack
              uses: slackapi/slack-github-action@v1.26.0
              with:
                  payload: |
                    {
                      "browser": "Focus",
                      "foo": "bar"
                    }    
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK