name: "Test webhooks"
    
on:
    workflow_dispatch:

jobs:
    call-webhooks:
        runs-on: macos-14
        steps:
            - name: Hello World!
              run: |
                echo "Hello World!"
                echo "\
                {\
                  blocks: [\
                  {\
                    type: 'divider'\
                  }\
                  ]\
                }" > slack.json
                cat slack.json
                #jq -n --arg type 'divider' '$ARGS.named' | \
                #  jq -n '.blocks|=[inputs]' > slack.json
                # jq -n --arg blocks '[]' '$ARGS.named' > slack.json
            - name: Report to Slack
              id: slack
              uses: slackapi/slack-github-action@v1.26.0
              with:
                payload: |
                  {
                    "blocks":[
                      {
                        "type": "header",
                        "text": {
                          "type": "plain_text",
                          "text": ":white_check_mark: $browser iOS $test_plan - $ios_simulator $ios_version ($branch)",
                          "emoji": true
                        }
                      },
                      {
                        "type":"divider"
                      }
                    ]
                  }
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_TEST_INFRA_ALERTS_WEBHOOK }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK